// <auto-generated />

#nullable disable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace SolarPanel.Infrastructure.Data.Migrations.SolarData
{
    [DbContext(typeof(SolarPanelDbContext))]
    [Migration("20250909165356_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolarPanel.Core.Entities.BatteryData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatteryCapacity")
                        .HasColumnType("int");

                    b.Property<decimal>("BatteryChargingCurrent")
                        .HasColumnType("decimal(5,1)");

                    b.Property<decimal>("BatteryDischargeCurrent")
                        .HasColumnType("decimal(5,1)");

                    b.Property<decimal>("BatteryVoltage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("BatteryVoltageFromScc")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("SolarDataId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SolarDataId")
                        .IsUnique();

                    b.ToTable("BatteryData");
                });

            modelBuilder.Entity("SolarPanel.Core.Entities.PowerData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AcInputFrequency")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("AcInputVoltage")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("AcOutputActivePower")
                        .HasColumnType("int");

                    b.Property<int>("AcOutputApparentPower")
                        .HasColumnType("int");

                    b.Property<decimal>("AcOutputFrequency")
                        .HasColumnType("decimal(4,1)");

                    b.Property<int>("AcOutputLoad")
                        .HasColumnType("int");

                    b.Property<decimal>("AcOutputVoltage")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("PvInputCurrent")
                        .HasColumnType("decimal(5,1)");

                    b.Property<int>("PvInputPower")
                        .HasColumnType("int");

                    b.Property<decimal>("PvInputVoltage")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("SolarDataId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SolarDataId")
                        .IsUnique();

                    b.ToTable("PowerData");
                });

            modelBuilder.Entity("SolarPanel.Core.Entities.SolarData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BusVoltage")
                        .HasColumnType("float");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CommandDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("InverterHeatSinkTemperature")
                        .HasColumnType("int");

                    b.Property<bool>("IsAcChargingOn")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBatteryVoltageToSteadyWhileCharging")
                        .HasColumnType("bit");

                    b.Property<bool>("IsChargingOn")
                        .HasColumnType("bit");

                    b.Property<bool>("IsChargingToFloat")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConfigurationChanged")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLoadOn")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSbuPriorityVersionAdded")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSccChargingOn")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSccFirmwareUpdated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSwitchedOn")
                        .HasColumnType("bit");

                    b.Property<int>("Rsv1")
                        .HasColumnType("int");

                    b.Property<int>("Rsv2")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("SolarData");
                });

            modelBuilder.Entity("SolarPanel.Core.Entities.BatteryData", b =>
                {
                    b.HasOne("SolarPanel.Core.Entities.SolarData", "SolarData")
                        .WithOne("BatteryData")
                        .HasForeignKey("SolarPanel.Core.Entities.BatteryData", "SolarDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolarData");
                });

            modelBuilder.Entity("SolarPanel.Core.Entities.PowerData", b =>
                {
                    b.HasOne("SolarPanel.Core.Entities.SolarData", "SolarData")
                        .WithOne("PowerData")
                        .HasForeignKey("SolarPanel.Core.Entities.PowerData", "SolarDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolarData");
                });

            modelBuilder.Entity("SolarPanel.Core.Entities.SolarData", b =>
                {
                    b.Navigation("BatteryData");

                    b.Navigation("PowerData");
                });
#pragma warning restore 612, 618
        }
    }
}
