// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SolarPanel.Infrastructure.Data;

#nullable disable

namespace SolarPanel.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SolarPanelDbContext))]
    [Migration("20250904110605_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SolarPanel.Core.Entities.BatteryData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BatteryCapacity")
                        .HasColumnType("integer");

                    b.Property<decimal>("BatteryChargingCurrent")
                        .HasColumnType("decimal(5,1)");

                    b.Property<decimal>("BatteryDischargeCurrent")
                        .HasColumnType("decimal(5,1)");

                    b.Property<decimal>("BatteryVoltage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("BatteryVoltageFromScc")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("SolarDataId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SolarDataId")
                        .IsUnique();

                    b.ToTable("BatteryData");
                });

            modelBuilder.Entity("SolarPanel.Core.Entities.PowerData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AcInputFrequency")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("AcInputVoltage")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("AcOutputActivePower")
                        .HasColumnType("integer");

                    b.Property<int>("AcOutputApparentPower")
                        .HasColumnType("integer");

                    b.Property<decimal>("AcOutputFrequency")
                        .HasColumnType("decimal(4,1)");

                    b.Property<int>("AcOutputLoad")
                        .HasColumnType("integer");

                    b.Property<decimal>("AcOutputVoltage")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("PvInputCurrent")
                        .HasColumnType("decimal(5,1)");

                    b.Property<int>("PvInputPower")
                        .HasColumnType("integer");

                    b.Property<decimal>("PvInputVoltage")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("SolarDataId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SolarDataId")
                        .IsUnique();

                    b.ToTable("PowerData");
                });

            modelBuilder.Entity("SolarPanel.Core.Entities.SolarData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("BusVoltage")
                        .HasColumnType("double precision");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CommandDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("InverterHeatSinkTemperature")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAcChargingOn")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBatteryVoltageToSteadyWhileCharging")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsChargingOn")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsChargingToFloat")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConfigurationChanged")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLoadOn")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSbuPriorityVersionAdded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSccChargingOn")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSccFirmwareUpdated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSwitchedOn")
                        .HasColumnType("boolean");

                    b.Property<int>("Rsv1")
                        .HasColumnType("integer");

                    b.Property<int>("Rsv2")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("SolarData");
                });

            modelBuilder.Entity("SolarPanel.Core.Entities.BatteryData", b =>
                {
                    b.HasOne("SolarPanel.Core.Entities.SolarData", "SolarData")
                        .WithOne("BatteryData")
                        .HasForeignKey("SolarPanel.Core.Entities.BatteryData", "SolarDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolarData");
                });

            modelBuilder.Entity("SolarPanel.Core.Entities.PowerData", b =>
                {
                    b.HasOne("SolarPanel.Core.Entities.SolarData", "SolarData")
                        .WithOne("PowerData")
                        .HasForeignKey("SolarPanel.Core.Entities.PowerData", "SolarDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolarData");
                });

            modelBuilder.Entity("SolarPanel.Core.Entities.SolarData", b =>
                {
                    b.Navigation("BatteryData");

                    b.Navigation("PowerData");
                });
#pragma warning restore 612, 618
        }
    }
}
